Add support for new Slonik sql literal syntax
thebearingedge/vscode-sql-lit pull request #5
Opened 2022-08-26 19:33 UTC by aust1nz

This change supports syntax highlighting for new [Slonik sql literal syntax](https://github.com/gajus/slonik#user-content-slonik-runtime-validation-example-use-of-sql-type), i.e.:

```ts
sql.type(zodModel)`SELECT * From users;`;
```

2022-08-26 21:00 UTC, thebearingedge commented
Thank you! I will get this integrated tomorrow morning 👍👍👍

2022-08-27 17:39 UTC, thebearingedge commented
@aust1nz Thanks for the contribution. Right now I'm getting the `.type()` call and argument highlighted as the template start.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/7432943/187041598-5ee4994a-9e8a-4ee2-9131-c7ef3a4b90db.png">

However, if you update the captures indexes, it seems to work as expected

```json
      "beginCaptures": {
        "0": {
          "name": "entity.name.function.tagged-template.js"
        },
        "2": {
          "patterns": [
            {
              "include": "source.ts#type-arguments"
            }
          ]
        },
        "3": {
          "name": "punctuation.definition.string.template.begin.js string.template.js"
        }
      },
```
👇 
```json
      "beginCaptures": {
        "0": {
          "name": "entity.name.function.tagged-template.js"
        },
        "2": {
          "patterns": [
            {
              "include": "source.ts#type-arguments"
            }
          ]
        },
        "3": {
          "patterns": [
            {
              "include": "source.ts"
            }
          ]
        },
        "4": {
          "name": "punctuation.definition.string.template.begin.js string.template.js"
        }
      }
```


<img width="568" alt="image" src="https://user-images.githubusercontent.com/7432943/187041667-b865d831-edd2-4888-997b-b801a545f8cd.png">

2022-08-27 17:41 UTC, thebearingedge requested changes
https://github.com/thebearingedge/vscode-sql-lit/pull/5#issuecomment-1229233977

2022-08-28 23:27 UTC, aust1nz commented
Noted your thoughts on improving the syntax highlighting, and updated the pull. Thank you!

2022-08-29 01:24 UTC, thebearingedge approved these changes

2022-08-29 01:25 UTC, thebearingedge commented
Thank you so much, will get a new release out soon 👍

2022-08-29 01:25 UTC, merged

2022-09-06 14:35 UTC, austinzentzkippdc commented
This is referenced as the [preferred VSCode extension for Slonik](https://github.com/gajus/slonik#user-content-slonik-syntax-highlighting-vs-code-syntax-highlighting-extension) now. Thanks!